사용자 기본 JPA Entity(Member) 생성
share-it-cuk/share-it-backend pull request #1
Opened 2024-03-14 12:58 UTC by greensnapback0229

[x] 패키지 생성
### Entity, JpaReposiotry package
 - Entity, JpaRepository 전용 `Domain` 하위 패키지 생성

### Member.class
 - Campus Entity 연관관계 맵핑 (Campus.class 생성)
 - Builder 생성자 생성
 -  초기 개발 편의성을 위해 `nullable` (spring security 적용 때문에)
    추후 추가 대부분 추가 예정
 - 역할 `enum`적용 (String 저장)
 - nickname `uniqueConstraint` 적용

### Role.class
 - Memeber Entity의 enum 클래스
 - `value()` 메소드로 값 가져오기

2024-03-14 14:42 UTC, devkeon requested changes

2024-03-14 14:42 UTC, devkeon commented on src/main/java/com/shareit/shareit/domain/entity/Member.java
> +		columnNames = "NICKNAME"
column 이름이 다릅니다! 확인 부탁드립니다.

2024-03-14 14:42 UTC, devkeon commented on src/main/java/com/shareit/shareit/domain/entity/Member.java
> +	@Column(name = "profile_key")
이거 column 이름 하나하나 다 안주셔도 돼요! 어차피 알아서 스네이크로 변환돼서 들어갑니다! 이러면 보기 더 어려워지는 감이 없지 않은 것 같습니다!

2024-03-14 14:42 UTC, devkeon commented on src/main/java/com/shareit/shareit/domain/Role.java
> +	ROLE_GRABBER("ROLE_GRABBER"),
혹시 빌려주는 사람과 받는 사람을 enum으로 구분하신 이유가 있으신가요??

2024-03-14 14:42 UTC, devkeon commented on src/main/java/com/shareit/shareit/domain/Repository/MemberRepository.java
> +	Member findAllBy(Long id);
id는 하나에만 존재하는데 findAll인걸 보니 다 끌어오는건가요?? 해당 메서드의 의도가 궁금합니다.

2024-03-14 14:48 UTC, greensnapback0229 commented on src/main/java/com/shareit/shareit/domain/Role.java
> +	ROLE_GRABBER("ROLE_GRABBER"),
일단 선택지를 늘려 놓은 겁니다..!
사실 role에 대한 필요성에 대해서 고민이 있습니다
그냥 아직 admin과 user에 대한 구분도 크게 의미가 없는 것 같아서요

2024-03-14 14:48 UTC, greensnapback0229 commented on src/main/java/com/shareit/shareit/domain/entity/Member.java
> +		columnNames = "NICKNAME"
헉 감사합니다

2024-03-14 14:51 UTC, greensnapback0229 commented on src/main/java/com/shareit/shareit/domain/entity/Member.java
> +	@Column(name = "profile_key")
아하 이게 더 가독성이 떨어질까요 필요한 것만 남겨 놓도록 하겠습니다 그럼

2024-03-14 14:52 UTC, devkeon commented on src/main/java/com/shareit/shareit/domain/Role.java
> +	ROLE_GRABBER("ROLE_GRABBER"),
role은 spring security 사용하려면 필요합니다. 그리고 social 과 user 도 구분해줘야 하기 때문에 추후에 이 부분은 필요한데 lender 와 grabber로 구분 짓는 부분은 뭔가 안맞는 것 같아서 질문드렸습니다!

2024-03-14 15:00 UTC, devkeon commented on src/main/java/com/shareit/shareit/domain/Repository/MemberRepository.java
> +	Member findAllBy(Long id);
추가로 이렇게 Member만 놓으시면 안되고 Optional로 감싸셔야 합니다. 안그러면 npe 위험이 있습니다...

2024-03-15 05:59 UTC, greensnapback0229 commented on src/main/java/com/shareit/shareit/domain/entity/Member.java
> +		columnNames = "NICKNAME"
지금 확인해 보니 column명 잘못된게 없는거 같은데 어떤 부분일까요..? 
저 name은 constraint 조건 이름입니다

2024-03-15 06:01 UTC, devkeon commented on src/main/java/com/shareit/shareit/domain/entity/Member.java
> +		columnNames = "NICKNAME"
그거 말고 columnNams요. "nickname" 입니다. 저희 컬럼명 소문자..

2024-03-15 06:22 UTC, greensnapback0229 commented on src/main/java/com/shareit/shareit/domain/entity/Member.java
> +		columnNames = "NICKNAME"
아 이거 ddl에서 자동변환 되긴 합니다. 보기 편하게 바꿔두겠슴다

2024-03-15 06:28 UTC, devkeon commented on src/main/java/com/shareit/shareit/domain/entity/Member.java
> +		columnNames = "NICKNAME"
아 이것도 자동 변환해주나요?? 몰랐네요..감사합니다!

2024-03-15 09:36 UTC, devkeon approved these changes

2024-03-15 09:36 UTC, merged